# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'egGroup' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for egGroup

  target 'egGroup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

    pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  end

  target 'egGroupTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'egGroup-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for egGroup-tvOS

  target 'egGroup-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
